version: 2

models:
  - name: stg_prices
    description: "Cleaned price data from CoinGecko"
    columns:
      - name: coin_id
        description: "Unique identifier for the coin"
        tests:
          - not_null
          # REMOVED unique test - coin_id appears multiple times (one per fetch)
      - name: current_price
        description: "Current price in USD"
        tests:
          - not_null
      - name: fetch_timestamp
        description: "When this data was fetched"
        tests:
          - not_null

  - name: stg_sentiment
    description: "Cleaned sentiment data from Fear & Greed Index"
    columns:
      - name: value
        description: "Sentiment score 0-100"
        tests:
          - not_null
      - name: fetch_timestamp
        tests:
          - not_null